         why numpy over list?
         fast-contiguoes
         memory efficent
         convenience
         multidimensional arrays
         rich mathemitical
         

In [3]:
import numpy as np  

In [4]:
import numpy as np #used ffor data handling and 2d adn 1d array
n1 = np.array([3,4,5,6])
print(n1)

[3 4 5 6]


In [4]:
#creating 2d array
n2 =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(n2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
#how to priint zero filled 22d array
n3  =np.zeros([5,8], dtype = 'int')
print(n3)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [6]:
#creating 3 dimentional arrau
n4=np.ones([2,3,3],dtype = 'int') #-> [2,3,3] -> 2-rendu 2 d array , 3 and 3 are the 3 cross 3 matrixes we need
print(n4)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [7]:
# how to create array of a some set of range of array like we nee a array neteweern 1-10
n8 = np.arange(10,40,2)
print(n8)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [8]:
#we can also create empty arry
n6 = np.empty([1,3],dtype ="int")
print(n6)

[[1835627552  170816357  538976288]]


In [9]:
n8 = np.arange(1,40,2,dtype = 'float')            #->(start,stop,step,dtype)
print(n8)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39.]


In [6]:
n9 = np.linspace(2,200 , num =100, dtype = 'int') #- > (start,stop,num=50,end=true) #num is the how much number we want
print(n9)
# linsapce  is used to create the 1d aray evenly spaced within  as specified intterval 

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


# logspace 
usde to craete 1d arr values evenly spaced on a logarthmitic scal with spefic range
 What is np.logspace()?
numpy.logspace(start, stop, num=50, base=10.0, endpoint=True)

It returns num values evenly spaced on a log scale, from:

base
start
to
base^
stop
base ^
start
 tobase ^
stop
 


In [22]:
n0 = np.logspace(1,40,2,dtype = 'i')            #->(start,stop,step,dtype)
print(n0)

[         10 -2147483648]


C:\Users\ragul\anaconda3\Lib\site-packages\numpy\core\function_base.py:299: RuntimeWarning: invalid value encountered in cast
  return _nx.power(base, y).astype(dtype, copy=False)


In [24]:
import numpy as np

arr = np.logspace(1, 3, num=5, base=20 , endpoint = True )
print(arr)


[  20.          89.4427191  400.        1788.854382  8000.       ]


In [7]:
n8 = np.linspace(-5,5,num =1000,dtype = 'f', endpoint = True) # include s the stop lst vaeu that means 5 and false meand that excluudes the 5 and print all than that)            #->(start,stop,step,dtype)
print(n8)

[-5.         -4.9899898  -4.97998    -4.9699697  -4.95996    -4.9499497
 -4.93994    -4.9299297  -4.91992    -4.9099097  -4.8999     -4.8898897
 -4.87988    -4.8698697  -4.85986    -4.8498497  -4.83984    -4.8298297
 -4.81982    -4.8098097  -4.7998     -4.7897897  -4.77978    -4.7697697
 -4.75976    -4.7497497  -4.73974    -4.7297297  -4.71972    -4.7097096
 -4.6997     -4.6896896  -4.67968    -4.6696696  -4.65966    -4.6496496
 -4.63964    -4.6296296  -4.61962    -4.6096096  -4.5995994  -4.5895896
 -4.5795794  -4.5695696  -4.5595593  -4.5495496  -4.5395393  -4.5295296
 -4.5195193  -4.5095096  -4.4994993  -4.4894896  -4.4794793  -4.4694695
 -4.4594593  -4.4494495  -4.4394393  -4.4294295  -4.4194193  -4.4094095
 -4.3993993  -4.3893895  -4.3793793  -4.3693695  -4.3593593  -4.3493495
 -4.3393393  -4.3293295  -4.3193192  -4.3093095  -4.2992992  -4.2892895
 -4.279279   -4.2692695  -4.259259   -4.2492495  -4.239239   -4.2292295
 -4.219219   -4.2092094  -4.199199   -4.189189   -4.179179   -4.

In [26]:
#we can als fill in the empty rray se the cell 7
n6.fill(9)
print(n6)

[[9 9 9]]


In [11]:
# how to acces the array vaues by their index

In [8]:
print(n1[2])

5


In [58]:
print(n1[::1])

[3 4 5 6]


In [60]:
print(n8[2:30:2])

[14 18 22 26 30 34 38]


In [12]:
print(n4[1,2]) # -> row column 2d rray
print(sum(n4[1]))


NameError: name 'n4' is not defined

In [10]:
#change the value in the 3 d marix
#firt
print(n4)                                  # the below 3d has the two matrix o and 1
#if i want to change he values with the respective matrix ie. 0 or 1 and specify the colum adn row 


NameError: name 'n4' is not defined

In [69]:
n4[0,1,2]  = 50
n4[1,2,2]  = 60

In [21]:
print(n4)

NameError: name 'n4' is not defined

shaping adnd slicing 

In [22]:
print(n4.shape)

(2, 3, 3)


In [23]:
print(n4.size)

18


In [24]:
print(n4.dtype)

int32


In [25]:
print(n4.ndim) # ndim gives the dimnsion of a matrix or the axi f the martrix

3


In [26]:
print(n4.nbytes) # ndim gives the dimnsion of a matrix or the axi f the martrix

72


sorting

In [27]:
ss = np.sort([1,2,3,6,9,3,2,7,9,15])   # 1d sort
print(ss)

[ 1  2  2  3  3  6  7  9  9 15]


In [30]:
 
sd = np.sort([[10,9,8,7,4,3,2,1,150], [14,400,35,23,65,2332,445,234,10]])   # 2d sort
print(sd)

[[   1    2    3    4    7    8    9   10  150]
 [  10   14   23   35   65  234  400  445 2332]]


# if you sort
by coloum 1
2
3 #ike that

In [26]:
sm = np.sort(sd , axis = 0)
print(sm)



[[   1    2    3    4    7    8    9   10  150]
 [  10   14   23   35   65  234  400  445 2332]]


reshape the array


In [25]:
n1 = np.array(5,6,7,8][1,2,3,4,)
print(n1)

[1 2 3 4 5 6 7 8]


In [28]:
n10 = n1.reshape(2,4) 
print(n10)

[[1 2 3 4]
 [5 6 7 8]]


In [31]:
#joining the 2 arays
n11 = np.arange(1,5)
print(n11)
n12 = np.arange(5,9)
print(n12)

[1 2 3 4]
[5 6 7 8]


In [32]:
#we can concat
n13 = np.concatenate((n11,n12))
print(n13)

[1 2 3 4 5 6 7 8]


In [33]:
n14 = n13[np.newaxis,:]
print(n14)


print(n14.shape)

[[1 2 3 4 5 6 7 8]]
(1, 8)


In [97]:
n16 = n13[:,np.newaxis]
print(n16 )
print(n16.shape)

NameError: name 'n13' is not defined

index  and the slicing

In [41]:
new = np.arange(10)
print(new)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
print(new>3) # thise check the value not filter it by the condition right but the below is verce visa
neww = new > 5
print(new[neww])

[False False False False  True  True  True  True  True  True]
[6 7 8 9]


In [48]:
print(new[3:9:2]) #3 start , 9 stop , 2 step

[3 5 7]


stack adn split

In [65]:
n22 = np.array([[1,2,3],[4,5,6]])
n33 = np.array([[1,2,3],[4,5,6]])
n44 = np.hstack((n22,n33 ))     #hstack → horizontal (adds columns). #vstack → vertical (adds rows
n45 = np.vstack((n22,n33 ))
print(n44)


[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [66]:
print(n45)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [35]:
n1 = np.array([1,2,3,4,5,6,7,8])
summ = n1.sum()
print(summ)
print(n1.mean())
 

36
4.5


# data types for numpy

In [6]:
#datetime 
import numpy as np
date_1 = np.datetime64('20024-07-06')
date_2 = np.datetime64('20029-07-06')
time_difference = date_1 - date_2
print(time_difference)
print(type(time_difference))

-1826 days
<class 'numpy.timedelta64'>


In [8]:
date_time = np.datetime64('2005-07-06 13:00:00')
print(date_time)
print(type(date_time))

2005-07-06T13:00:00
<class 'numpy.datetime64'>


# object we can create the multiple dataye iinside the array


In [14]:
import numpy as np
obj = np.array([1,2,3.0,False,[1,2,3,24],'rahul'] , dtype = object)
print(obj)
print(type(obj))


[1 2 3.0 False list([1, 2, 3, 24]) 'rahul']
<class 'numpy.ndarray'>


# datatype converstion

In [19]:
#int to float
ar = np.array([1,2,3,4])
ar_float =  ar.astype(np.float64)
print(type(ar_float))


<class 'numpy.ndarray'>


In [24]:
#float to int
ar_float = np.array([3.4,1.5,6.5,3.4,2.1] ,dtype = 'f')
ar_int = ar_float.astype(np.int32)
print(ar_float)
print(ar_int)
print(type(ar_float))

[3.4 1.5 6.5 3.4 2.1]
[3 1 6 3 2]
<class 'numpy.ndarray'>


# array attributes

In [1]:
import numpy as np
ar = np.array([1,2,3,4,5,3837,2,8590,43598,43885790394])
print(ar.shape)

(10,)


In [4]:
import numpy as np
a = np.array([
    [1,2,3],
    [1,2,3]
])
print(a.shape)
print(a.ndim)
print(a.strides)  #--> strides means Think of a NumPy array as a table stored in memory (like in a notebook).The strides tell Python how far to jump in memory to reach the next element.
print(list(a.flat))


(2, 3)
2
(12, 4)
[1, 2, 3, 1, 2, 3]


In [9]:
import numpy as np
a = np.array([10, 20, 30, 40], dtype=np.int32)#Each number (int32) = 4 bytes.To go from 10 → 20, Python jumps 4 bytes. So stride = 4.
print(a.strides)
b = np.array([[1, 2, 3 ,4, 5],
              [4, 5, 6, 6 ,6]], dtype=np.int32)
print(b.strides)

#To move down one row (from 1 to 4), Python skips 12 bytes (because one row has 3 numbers × 4 bytes).

#To move right one column (from 1 to 2), Python skips 4 bytes (just one number).

(4,)
(20, 4)


# nd ara vs aray

In [43]:
arr # -> 1 object = np.array([1,2,3,4,4]) # -> array 
print(arr) #arr-> nd array we can do operations on that 



[1 2 3 4 4]


In [11]:
arr = np.array([
    [1,2,3],
    [2,4,5]
])


print(arr)

[[1 2 3]
 [2 4 5]]


In [17]:
print(arr.max())
print(arr.max(axis = 0))
#    [1,2,3] ->  axis =0 means colum like it checcks the 1 and 2 whuich max ant  2,4 whd nexich max and impotant *** if you give arr.max() i will give max num in arr
    #[2,4,5]

print(arr.min(axis = 1))

5
[2 4 5]
[1 2]


print(arr.argmax())
print(ar.argmax())


b = np.array([[1, 3], [7, 2]]) # -> [0,1],[2,3]
print(np.argmax(b))  # Output: 2 (index in flattened array, max is 7)


# getting array from existing data that data stored in tuple list dict and all kind like pandas series


In [20]:
import pandas as pd
c = pd.Series([1,2,3,4,5,6,6,6,54,4])
c.head()
# if you wnte to convert teh series into pandas then use asarray function


0    1
1    2
2    3
3    4
4    5
dtype: int64

# crr = np.asarray(c)# ->asarray changes to array form the seris
# print(crr)

In [21]:
crr = np.asarray(c) 
print(crr)

[ 1  2  3  4  5  6  6  6 54  4]


# numpy brocasting used for sme operations like 2d array add the array

# rule 1 -> arrays with same shape are compatible ,if not exiest the rule then we cannot use btodcastig


In [23]:
import numpy as np
a = np.array([1,2,3,4])#-> shape is 1,3
b = np.array([1,2,3,4])# shape is 1,3
c = a+b
print("the addition values ar:",c)

the addition values ar: [2 4 6 8]


# the addition values ar: [2 4 6 8]


# rule 2 -> arrays with dimension of size 1 are streched or repeated along that dimension
# eg [2,3,1]->shape1,3  nd [2,3,4] ->shape 2,3    ---> it will return the it will streched like [2,3,1] 3 tuimes
   #                         [4,5,6]

# shepe (1,3) and shpe(4,3)
# shape(2,1) and (2,3)
#(1,1) and (3,1)

# rule 3 arrays with size 1 in a particular dimesion act as if they had the size of max shape zlongb that dimension
# Ex division of 1 dimensitiona arrey by a scalar 

In [25]:
# rule 2
n1 = np.array([[1,2,3]])# -> thise expands the same row 4 times to add() like [[[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]]] like thise so it can add smothelly
n2 = np.array([[2,3,4],
               [3,4,5],
               [5,4,3],
               [4,5,6]])
addition = n1+n2
print(addition)

[[3 5 7]
 [4 6 8]
 [6 6 6]
 [5 7 9]]


In [18]:
#rule 3 scalar


In [26]:
n1 = np.array([[1,2,3],
               [3,4,5],
               [5,4,3],
               [4,5,6]])
s = 10
new_arr = 10-n1
print(new_arr) # subracts the matrix with the scalar value


[[9 8 7]
 [7 6 5]
 [5 6 7]
 [6 5 4]]


# another method to create array 
# frombuffer --> creates a new 1d arr from buffer obj, buff obj is memeory stored in seq of bytes such a sstring ,bytes



# syntax         numpy.frombuffer(buffer_object , dtype = float ,count =-1,offset =0)

In [27]:
# buffer to array

In [27]:
import numpy as np

buffer_obj = b'\x01\x04\x05\x07'
ar = np.frombuffer(buffer_obj, dtype= np.uint8)

print(ar)



[1 4 5 7]


# ❓ Why dtype=np.uint8 is used here:
🔹 1. Each \xNN is 1 byte
b'\x01\x04\x05\x07' is a byte string, 4 bytes total.

uint8 = unsigned 8-bit integer = 1 byte.

So the buffer splits cleanly into 4 values: [1, 4, 5, 7].

# fromiter 
it creates a new one d aray from iterabel obj like tuple strings
syntax numpy.formitter(iteratable_obj , dtype , count =1)
itertable obh is called as the tuple and list

exaple 1

In [30]:
import numpy as np
lst = [1,2,3,4,5]
n = np.fromiter(lst,np.int32)
print(n)

[1 2 3 4 5]


In [42]:
#it is a array not list it retrives the list from and conver to the array proof
print(type(lst))
print(type(n))

<class 'list'>
<class 'numpy.ndarray'>


In [43]:
# u can use dict

In [36]:
dicet = {1:'ragul',2:'sujith',3:'kusu_siva',4:'balaji'}
new_arr_from_dict = np.fromiter( dicet.items(), dtype =np.chararray) # for  keys() dtype is int <> valus np.str but we need the both so do np.chararr
print(new_arr_from_dict)

[(1, 'ragul') (2, 'sujith') (3, 'kusu_siva') (4, 'balaji')]


# for loop

In [88]:
import numpy as np
arr = np.array([[1,2,3],
                [2,3,4],
                [6,7,8],
                [8,6,4]])
print(arr)
print(arr.size)

[[1 2 3]
 [2 3 4]
 [6 7 8]
 [8 6 4]]
12


In [93]:
for i in arr:
    print(i)
        

[1 2 3]
[2 3 4]
[6 7 8]
[8 6 4]


# iterte the 2d arraywith o/t nested loop by np.nditer

In [40]:
import numpy as np
arr = np.array([[1,3,4,5],
                [2,3,5,6]])
for i in np.nditer(arr,order = 'c'): #  c denotes the iteration should happen in rows wise like thise  --------> \n <------------
    print(i)                         #f  denotes the iteration should happen in colum wise like thise  --------> \n <------------

1
3
4
5
2
3
5
6


In [3]:
import numpy as np
arr = np.array([[1,3,4,5],
                [2,3,5,6]])
for i in np.nditer(arr,order = 'f'): #  c denotes the iteration should happen in rows wise like thise  --------> \n <------------
    print(i)    

1
2
3
3
4
5
5
6


In [10]:
# enumerate function it is used to iterate like np.nditer but print the indices alsoimport numpy as np
ar = np.array([[1,3,4,5],
                [2,3,5,6],
                [3,4,5,10]])
for i in np.ndenumerate(arr ): 
    print(i)

((0, 0), 1)
((0, 1), 3)
((0, 2), 4)
((0, 3), 5)
((1, 0), 2)
((1, 1), 3)
((1, 2), 5)
((1, 3), 6)
((2, 0), 3)
((2, 1), 4)
((2, 2), 5)
((2, 3), 10)


# update numpy array elements 
1)fill method
 2)direct assingment method (index nad slicing)
3)put methos
4)boolean indexing method

In [22]:
# 1) method np.fill -> fills the entire array with the specifiea value
# step like we are  having zero array
import numpy as np
arr = np.zeros(4)
print(arr)
arr.fill(10)      
print(arr)

[0. 0. 0. 0.]
[10. 10. 10. 10.]


# 2nd method for update aray

In [23]:
# dirext assignment  -> you can update array values by diretly assingning new values to specific indices or slices of the array

In [37]:
import numpy as np
arr = np.arange(1,10)
print(arr)# - >befor update 
arr[0:5] = [9,8,7,6,5]
print(arr) #-> after update
#for i in np.ndenumerate(arr):
    #print(i)
arr[0] = 100
print(arr)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 6 7 8 9]
[100   8   7   6   5   6   7   8   9]


# 3 rd method to update values

In [38]:
# put  -> update the new elements by only by [0,2,3] only indeies

In [44]:
import numpy as np
arr = np.array([1,4,6,4,3,2])
print("b4 update")
print(arr)
np.put(arr,[3,4,5],[100,100,100]) #-> arr name , it change  to be change , what to be replace
print("after update")
print(arr)


b4 update
[1 4 6 4 3 2]
after update
[  1   4   6 100 100 100]


# 4th method to updatevalues

In [46]:
import numpy as np
arr = np.array([1,4,6,4,3,2])
# update vaues grater than 3
arr[arr>3] = 100 # condition
print(arr)


[  1 100 100 100   3   2]


In [60]:
import numpy as np

arr = np.array([[1, 2, np.nan],
                [2, np.nan, 3],
                [np.nan, 5, 6]])

print("Before:")
print(arr)

arr[np.isnan(arr)] = 10

print("After replacing NaN with 10:")
print(arr)


Before:
[[ 1.  2. nan]
 [ 2. nan  3.]
 [nan  5.  6.]]
After replacing NaN with 10:
[[ 1.  2. 10.]
 [ 2. 10.  3.]
 [10.  5.  6.]]


import numpy as np

# Sample array of people's ages
ages = np.array([15, 22, 17, 18, 45, 16, 30, 12, 19, 70])

print("All ages:", ages)

# Get eligible voters (age >= 18)
eligible_voters = ages[ages >= 18]

print("Eligible voters (age >= 18):", eligible_voters)



# flatten method

In [15]:
import numpy as np
arr = np.array([[1, 2, 5],
                [2,4, 3],
                [6, 5, 6]])
print(arr)
ar = arr.flatten()

print(ar)

[[1 2 5]
 [2 4 3]
 [6 5 6]]
[1 2 5 2 4 3 6 5 6]


In [43]:
arr[0][0] = 10

In [44]:
print(ar)

[1 4 5 7]


In [45]:
print(arr)

[[10  3  4  5]
 [ 2  3  5  6]]


# ravel meathod
it is a method that the orignal array is changed when the cpied array also changes 

In [5]:
import numpy as np
arr = np.array([[1,2,10239,5],
                [2,3,4,5]])
print(arr) # original arraay



[[    1     2 10239     5]
 [    2     3     4     5]]


In [6]:
ar = arr.ravel()
print(ar)  # converst the 2d into 1d 

[    1     2 10239     5     2     3     4     5]


In [7]:
#if i changes the ar aarray it reflects in the main arrr


In [50]:
ar[0] = 100;

In [51]:
print(arr)

[[100   3   4   5]
 [  2   3   5   6]]


# numpy transpose

In [46]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
ar = np.transpose(arr)
print(arr)
print(ar) # it changes the coloum into rows and rows into coloums

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


# using spliting operations breaking the arrays into multiple sub arrays

In [53]:
arr = np.array([1,2,3,4,5,5,5,64,6,6,7,7,8,67,7])
n = np.split(arr,3)
print(n) #subarray

[array([1, 2, 3, 4, 5]), array([ 5,  5, 64,  6,  6]), array([ 7,  7,  8, 67,  7])]


In [9]:
n = np.array([[1,2,3],[2,3,4],[2,3,4]])
print(n)

[[1 2 3]
 [2 3 4]
 [2 3 4]]


In [10]:
a= np.sum(n[2]) #n[2] is the row add and the n[:,3]
 #or any number 2 1 are the colum sum 
print(a)

9


In [21]:
import numpy as np
n = np.array([1,2,3,4,5,6])
print(n) # befoe resize
m = np.resize(n,(1,10))# --> size should be defined there
print(m)
print(n)

[1 2 3 4 5 6]
[[1 2 3 4 5 6 1 2 3 4]]
[1 2 3 4 5 6]


# appending to the array like you can append numebrs and arrays


In [40]:
arr = np.array([[1,2,3,4],[2,3,4,5],[2,3,4,5]])
print(arr) # b4 appending
print("----------")
arr1 = np.array([4,4,4,4])
arrr = np.append(arr,[arr1] ,axis =0)

print(arrr)

[[1 2 3 4]
 [2 3 4 5]
 [2 3 4 5]]
----------
[[1 2 3 4]
 [2 3 4 5]
 [2 3 4 5]
 [4 4 4 4]]


In [41]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

new_col = np.array([[10],
                    [20],
                    [30]])

# Option 1: using np.append
result = np.append(arr, new_col, axis=1)
print(result)

[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


In [46]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]) #np.insert(arr, index, value, axis=…)
#insert operaton
arr[2,2] =10213
print(arr)

[[    1     2     3]
 [    4     5     6]
 [    7     8 10213]]


In [ ]:
new_row = [[100, 101, 102], [200, 201, 202]]  # one row per matrix
result = np.insert(arr, 1, [100, 101, 102], axis=1)

print(result)
